language: c
group: travis_latest

addons:
  apt:
    packages:
    - octave

script:
- octave-cli simpleTest.m # Running a MATLAB/Octave script
- octave-cli eval "rand(4)" # Evaluate a function from Octave CLI